project_id = "qvrvcvmoudxchipvzksh"

[functions.ai-advisor-chat]
verify_jwt = false

[functions.ai-content-optimizer]
verify_jwt = false

[functions.analyze-visual-content]
verify_jwt = false

[functions.content-enhancer]
verify_jwt = false

[functions.generate-blog-image]
verify_jwt = false

[functions.generate-external-links]
verify_jwt = false

[functions.humanize-content]
verify_jwt = false
