project_id = "qvrvcvmoudxchipvzksh"

[functions.auto-publish-scheduled]
verify_jwt = false

[functions.ai-advisor-chat]
verify_jwt = false

[functions.ai-content-optimizer]
verify_jwt = false

[functions.analyze-blog-content]
verify_jwt = false

[functions.analyze-visual-content]
verify_jwt = false

[functions.content-enhancer]
verify_jwt = false

[functions.generate-blog-image]
verify_jwt = false

[functions.generate-external-links]
verify_jwt = false

[functions.generate-internal-links]
verify_jwt = false

[functions.humanize-content]
verify_jwt = false

[functions.calculate-ai-score]
verify_jwt = false

[functions.generate-speakable-answer]
verify_jwt = false

[functions.ai-link-insertion]
verify_jwt = false

[functions.validate-and-fix-links]
verify_jwt = false

[functions.monitor-external-links]
verify_jwt = false

[functions.optimize-external-links]
verify_jwt = false

[functions.bulk-repair-links]
verify_jwt = false

[functions.embed-image-metadata]
verify_jwt = false

[functions.generate-seo-fields]
verify_jwt = false

[functions.generate-cluster-metadata]
verify_jwt = false

[functions.rebuild-sitemaps]
verify_jwt = false

[functions.batch-generate-speakable]
verify_jwt = false

[functions.generate-160-summary]
verify_jwt = false
