name: Generate Static HTML for AI Crawlers

on:
  push:
    branches: [ main ]
  schedule:
    # Run daily at 2 AM UTC to regenerate static files
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  generate-html:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate static HTML files
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: npm run build:static
      
      - name: Commit and push if changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/static/
          git diff --quiet && git diff --staged --quiet || \
          (git commit -m "🤖 Auto-generate static HTML for AI crawlers [skip ci]" && git push)
